manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
# 1. Add HeeTuic as a new remote
    - name: heetuic
      url-base: https://github.com/HeeTuic
    - name: Good-Great-Grand-Wonderful
      url-base: https://github.com/Good-Great-Grand-Wonderful
    - name: SolidAlloy
      url-base: https://github.com/SolidAlloy
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      # 2. Tell West to use the new remote
      remote: heetuic
      # 3. Specify the exact repository name on that remote
      repo-path: zmk-for-crosses46-dual
      # 4. Your target commit hash goes here
      revision: bae0585c9f4dbb9764122629e8965bc29d27b142
      import: app/west.yml
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
    - name: gggw-zmk-keebs
      remote: SolidAlloy
      revision: zephyr-4.1
      import: config/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
