manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Good-Great-Grand-Wonderful
      url-base: https://github.com/Good-Great-Grand-Wonderful
    - name: SolidAlloy
      url-base: https://github.com/SolidAlloy
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      # We must point this to an official ZMK OS commit, NOT a config commit.
      # This is a known-stable commit from ZMK main before recent Zephyr 3.5 updates.
      revision: 8c12a42b0afaa9bc3a6c2084c68ba02fbafc21ee 
      import: app/west.yml
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
    - name: gggw-zmk-keebs
      remote: SolidAlloy
      revision: zephyr-4.1
      import: config/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
